### PR TITLE
Reverse an array

### PR DESCRIPTION
**Pull request by KonradLinkowski**

### CODE REVIEW

**Comment by phuocng** [comment]
Thank you for the PR, but I am not a fan of using an alias of native method. Otherwise, we will have a lot of snippets.

**Comment by KonradLinkowski** [comment]
I just wanted the `sort` method to be here.

**Comment by robinpokorny** [comment]
@KonradLinkowski The version with sort is not a good practice. Since the compare function always returns -1, it is not reflective and therefore the resulting order is implementation-specific. See https://tc39.es/ecma262/#sec-array.prototype.sort

**Comment by KonradLinkowski** [comment]
@robinpokorny using one-liners is usually a bad practice. Code is less readable when it's squished to one line. I don't mean simple operations.

**Pull request closed without merging**
